name: Build .NET Solution

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Sharp-O-Matic.Frontend/**'
      - 'src/Sharp-O-Matic.Editor/**'
      - 'src/Sharp-O-Matic.Engine/**'
      - 'src/Sharp-O-Matic.Server/**'
  pull_request:
    paths:
      - 'src/Sharp-O-Matic.Frontend/**'
      - 'src/Sharp-O-Matic.Editor/**'
      - 'src/Sharp-O-Matic.Engine/**'
      - 'src/Sharp-O-Matic.Server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore

      - name: Set build version
        run: echo "BUILD_VERSION=0.9.$((GITHUB_RUN_NUMBER-1))" >> $GITHUB_ENV

      - name: Build
        working-directory: src
        run: dotnet build --configuration Release --no-restore /p:Version=$BUILD_VERSION /p:AssemblyVersion=$BUILD_VERSION /p:FileVersion=$BUILD_VERSION

      - name: Test
        working-directory: src
        run: dotnet test --configuration Release --no-build --verbosity normal
